Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/08/2022
Var
// Seção de Declarações das variáveis 
controle : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 para controle <- 1 ate 10 passo 1 faca
    escreval("controle:", controle)
    fimpara

Fimalgoritmo