Algoritmo "REPITA1"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Edson Shinki Kaneshima 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Sarah Vitória Hernandes Gaspar
// Data atual  : 29/08/2022
Var
// Seção de Declarações das variáveis 
 nome : caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 repita
 escreval("Digite um nome: ")
 leia(nome)
 ate (nome = "Ana")

Fimalgoritmo